build_dir := "./build"
img_name := "sd.img"
fat_offset := "1M"
uboot_script := "./boot.cmd"
port := "8982"

build_dir:
    mkdir -p {{ build_dir }}

build: build_dir
    cargo objcopy --target armv6-none-eabihf --features semihosting -- -O binary {{ build_dir }}/kernel.img

build_7: build_dir
    cargo objcopy --target armv7a-none-eabihf --features semihosting -- -O binary {{ build_dir }}/kernel7.img

run_0: build
    qemu-system-arm --machine raspi0 --nographic --serial mon:stdio --no-reboot --kernel {{ build_dir }}/kernel.img --semihosting

run_1: build
    qemu-system-arm --machine raspi1ap --nographic --serial mon:stdio --no-reboot --kernel {{ build_dir }}/kernel.img --semihosting

run_2: build_7
    qemu-system-arm --machine raspi2b --nographic --serial mon:stdio --no-reboot --kernel {{ build_dir }}/kernel7.img --semihosting

run_virt: build_7
    # The default CPU for the `virt` machine is armv7a
    qemu-system-arm --machine virt --nographic --serial mon:stdio --no-reboot --kernel {{ build_dir }}/kernel7.img --semihosting -s --trace "*gic*"

# U-Boot works on real Raspberry Pis and on the qemu `virt` machine. It doesn't work in qemu `raspi` machines.
build_qemu_uboot_script: build_7
    mkimage -A arm -T script -C none -n "Hello World Script" -d {{ uboot_script }} {{ build_dir }}/boot.scr
    truncate -s 64M {{ build_dir }}/{{ img_name }}
    parted -s {{ build_dir }}/{{ img_name }} mklabel msdos mkpart primary fat32 2048s 100% set 1 boot on
    mformat -i {{ build_dir }}/{{ img_name }}@@{{ fat_offset }} -F -v "BOOT" ::
    mcopy -i {{ build_dir }}/{{ img_name }}@@{{ fat_offset }} {{ build_dir }}/boot.scr ::/boot.scr

    # mmd -i {{ build_dir }}/{{ img_name }}@@{{ fat_offset }} ::/boot
    # mmd -i {{ build_dir }}/{{ img_name }}@@{{ fat_offset }} ::/boot/extlinux
    # mcopy -i {{ build_dir }}/{{ img_name }}@@{{ fat_offset }} ./extlinux.conf ::/boot/extlinux/extlinux.conf
    # mcopy -i {{ build_dir }}/{{ img_name }}@@{{ fat_offset }} {{ build_dir }}/kernel7.img ::/boot/kernel.img

run_uboot: build_qemu_uboot_script build_7
    qemu-system-arm --machine virt --nographic --serial mon:stdio --no-reboot --bios $UBOOT_ARM --semihosting  -drive file=./build/{{ img_name }},format=raw,if=virtio,readonly=on -s

serve:
    http-server {{ build_dir }} -p {{ port }}

clippy:
    cargo clippy --target armv6-none-eabihf
    cargo clippy --target armv6-none-eabihf --features semihosting
    cargo clippy --target armv7a-none-eabihf
    cargo clippy --target armv7a-none-eabihf --features semihosting
