use core::{
    num::NonZero,
    ptr::NonNull,
    slice::{self},
    task::Poll,
};

use common::{
    ENV_PS2_KEYBOARD_CAPABILITY, EventStreamMem, QueueReader, SyscallSubscribeToKeyboard,
    SyscallSubscribeToKeyboardInput,
};
use futures::{Stream, stream::FusedStream};

use crate::{EnvEntries, ExecutorContext, syscall};

/// # Cancel Safety
/// Futures generated by the stream are cancel safe.
pub struct AsyncKeyboard<'a> {
    executor_context: &'a ExecutorContext,
    capability: NonZero<u64>,
    slots_len: NonZero<usize>,
    ptr: NonNull<EventStreamMem>,
}

impl<'a> AsyncKeyboard<'a> {
    /// Slots_len will be rounded up to `size_of::<usize>()`
    pub fn new(
        env: &EnvEntries,
        executor_context: &'a ExecutorContext,
        slots_len: NonZero<usize>,
    ) -> Self {
        let input = SyscallSubscribeToKeyboardInput {
            capability: NonZero::new(*env.get(&ENV_PS2_KEYBOARD_CAPABILITY).unwrap()).unwrap(),
            slots_len,
        };
        // Safety: The pointer points to valid memory
        let output = unsafe { syscall::<SyscallSubscribeToKeyboard>(&input) }.unwrap();
        Self {
            executor_context,
            capability: output.event,
            slots_len: output.slots_len,
            ptr: NonNull::new(output.addr.get() as *mut EventStreamMem).unwrap(),
        }
    }
}

impl Drop for AsyncKeyboard<'_> {
    fn drop(&mut self) {
        self.executor_context.take(self.capability);
        // TODO: Tell kernel that we're unsubscribing to the keyboard
        todo!()
    }
}

impl Stream for AsyncKeyboard<'_> {
    type Item = u8;

    fn poll_next(
        self: core::pin::Pin<&mut Self>,
        cx: &mut core::task::Context<'_>,
    ) -> core::task::Poll<Option<Self::Item>> {
        let s = self.get_mut();
        s.executor_context.take(s.capability);
        let mem = unsafe { s.ptr.as_mut() };
        let shared_slots_ptr = mem.slots.as_ptr();
        let shared_slots = unsafe { slice::from_raw_parts(shared_slots_ptr, s.slots_len.get()) };
        let mut reader = QueueReader::new(&mem.write_count, &mem.read_count, shared_slots);
        if let Some(data) = reader.pop() {
            Poll::Ready(Some(data))
        } else {
            s.executor_context.register_waker(s.capability, cx.waker());
            // Because reader.pop() returned None, we did not modify any data before returning Poll::Pending, making this future cancel safe
            Poll::Pending
        }
    }
}

impl FusedStream for AsyncKeyboard<'_> {
    fn is_terminated(&self) -> bool {
        false
    }
}
