use core::{
    mem::MaybeUninit,
    num::NonZero,
    slice::{self},
    sync::atomic::{AtomicU8, AtomicUsize},
    task::Poll,
};

use alloc::boxed::Box;
use common::{
    ENV_PS2_KEYBOARD_CAPABILITY, QueueReader, SyscallSubscribeToKeyboard,
    SyscallSubscribeToKeyboardInput,
};
use futures::{Stream, stream::FusedStream};

use crate::{EnvEntries, ExecutorContext, syscall};

#[derive(Debug)]
#[repr(C)]
struct M {
    write_count: AtomicUsize,
    read_count: AtomicUsize,
    slots: [AtomicU8; 0],
}

impl M {
    pub fn size(slots_len: usize) -> usize {
        size_of::<Self>() + size_of::<AtomicU8>() * slots_len
    }
}

/// # Cancel Safety
/// Futures generated by the stream are cancel safe.
pub struct AsyncKeyboard<'a> {
    executor_context: &'a ExecutorContext,
    capability: NonZero<u64>,
    b: Box<[MaybeUninit<usize>]>,
    slots_len: usize,
}

impl<'a> AsyncKeyboard<'a> {
    /// Slots_len will be rounded up to `size_of::<usize>()`
    pub fn new(env: &EnvEntries, executor_context: &'a ExecutorContext, slots_len: usize) -> Self {
        let slots_len = slots_len.next_multiple_of(size_of::<usize>());
        // We use usize for alignment
        let len = M::size(slots_len) / size_of::<usize>();
        let mut b = Box::<[usize]>::new_uninit_slice(len);
        let mem_ptr = b.as_mut_ptr().cast::<MaybeUninit<M>>();
        // Safety: The pointer is convertible to M
        let mem = unsafe { mem_ptr.as_mut() }.unwrap();
        mem.write(M {
            read_count: AtomicUsize::new(0),
            write_count: AtomicUsize::new(0),
            slots: [],
        });
        let input = SyscallSubscribeToKeyboardInput {
            capability: NonZero::new(*env.get(&ENV_PS2_KEYBOARD_CAPABILITY).unwrap()).unwrap(),
            queue_ptr: mem_ptr.addr(),
            slots_len,
        };
        // Safety: The pointer points to valid memory
        let capability = unsafe { syscall::<SyscallSubscribeToKeyboard>(&input) }.unwrap();
        Self {
            executor_context,
            capability,
            b,
            slots_len,
        }
    }
}

impl Drop for AsyncKeyboard<'_> {
    fn drop(&mut self) {
        self.executor_context.take(self.capability);
        // TODO: Tell kernel that we're unsubscribing to the keyboard
        todo!()
    }
}

impl Stream for AsyncKeyboard<'_> {
    type Item = u8;

    fn poll_next(
        self: core::pin::Pin<&mut Self>,
        cx: &mut core::task::Context<'_>,
    ) -> core::task::Poll<Option<Self::Item>> {
        let s = self.get_mut();
        s.executor_context.take(s.capability);
        let mem_ptr = s.b.as_mut_ptr().cast::<M>();
        let mem = unsafe { mem_ptr.as_mut() }.unwrap();
        let shared_slots_ptr = (s.b.as_ptr().addr() + size_of::<M>()) as *const AtomicU8;
        let shared_slots = unsafe { slice::from_raw_parts(shared_slots_ptr, s.slots_len) };
        let mut reader = QueueReader::new(&mem.write_count, &mem.read_count, shared_slots);
        if let Some(data) = reader.pop() {
            Poll::Ready(Some(data))
        } else {
            s.executor_context.register_waker(s.capability, cx.waker());
            // Because reader.pop() returned None, we did not modify any data before returning Poll::Pending, making this future cancel safe
            Poll::Pending
        }
    }
}

impl FusedStream for AsyncKeyboard<'_> {
    fn is_terminated(&self) -> bool {
        false
    }
}
