build_dir := absolute_path("./build")
img_name := "sd.img"
fat_offset := "1M"
uboot_script := "./boot.cmd"
port := "8982"

build_dir:
    mkdir -p {{ build_dir }}

[working-directory('arm')]
build: build_dir
    cargo objcopy --target armv6-none-eabihf --features semihosting -- -O binary {{ build_dir }}/kernel.img

[working-directory('arm')]
build_7: build_dir
    cargo objcopy --target armv7a-none-eabihf --features semihosting -- -O binary {{ build_dir }}/kernel7.img

[working-directory('aarch64')]
build_8: build_dir
    cargo objcopy --target aarch64-unknown-none-softfloat --features semihosting -- -O binary {{ build_dir }}/kernel8.img

[working-directory('riscv')]
build_riscv32: build_dir
    cargo objcopy --target riscv32imac-unknown-none-elf -- -O binary {{ build_dir }}/kernel_riscv32.img

[working-directory('riscv')]
build_riscv64: build_dir
    cargo objcopy --target riscv64gc-unknown-none-elf -- -O binary {{ build_dir }}/kernel_riscv64.img

run_0: build
    qemu-system-arm --machine raspi0 --nographic --serial mon:stdio --no-reboot --kernel {{ build_dir }}/kernel.img --semihosting

run_1: build
    qemu-system-arm --machine raspi1ap --nographic --serial mon:stdio --no-reboot --kernel {{ build_dir }}/kernel.img --semihosting

run_2: build_7
    qemu-system-arm --machine raspi2b --nographic --serial mon:stdio --no-reboot --kernel {{ build_dir }}/kernel7.img --semihosting

run_3: build_8
    qemu-system-aarch64 --machine raspi3b --nographic --serial mon:stdio --no-reboot --kernel {{ build_dir }}/kernel8.img --semihosting

run_4: build_8
    qemu-system-aarch64 --machine raspi4b --nographic --serial mon:stdio --no-reboot --kernel {{ build_dir }}/kernel8.img --semihosting

run_virt_arm: build_7
    # The default CPU for the `virt` machine is armv7a
    qemu-system-arm --machine virt --nographic --serial mon:stdio --no-reboot --kernel {{ build_dir }}/kernel7.img --semihosting

run_virt_aarch64: build_8
    qemu-system-aarch64 --machine virt --cpu cortex-a57 --no-reboot --nographic --serial mon:stdio --semihosting --kernel {{ build_dir }}/kernel8.img

run_virt_riscv32 *args: build_riscv32
    qemu-system-riscv32 --machine virt --no-reboot --nographic --serial mon:stdio --kernel {{ build_dir }}/kernel_riscv32.img {{ args }}

run_virt_riscv64: build_riscv64
    qemu-system-riscv64 --machine virt --no-reboot --nographic --serial mon:stdio --kernel {{ build_dir }}/kernel_riscv64.img

[working-directory('aarch64')]
elf_64:
    cargo build --target aarch64-unknown-none-softfloat --features semihosting
    readelf target/aarch64-unknown-none-softfloat/debug/kernel -S -r

[working-directory('riscv')]
readelf_riscv32:
    cargo build --target riscv32imac-unknown-none-elf
    readelf target/riscv32imac-unknown-none-elf/debug/kernel -h -S -r

[working-directory('riscv')]
readelf_riscv64:
    cargo build --target riscv64gc-unknown-none-elf
    readelf target/riscv64gc-unknown-none-elf/debug/kernel -h -S -r

[working-directory('aarch64')]
objdump:
    cargo objdump --target aarch64-unknown-none-softfloat --features semihosting -- -d --start-address=0x0 --stop-address=0x100

[working-directory('riscv')]
objdump_riscv32:
    cargo objdump --target riscv32imac-unknown-none-elf -- -d --start-address=0x0 --stop-address=0x300

# U-Boot works on real Raspberry Pis and on the qemu `virt` machine. It doesn't work in qemu `raspi` machines.
build_qemu_uboot_script:
    mkimage -A arm -T script -C none -n "Hello World Script" -d {{ uboot_script }} {{ build_dir }}/boot.scr
    truncate -s 64M {{ build_dir }}/{{ img_name }}
    parted -s {{ build_dir }}/{{ img_name }} mklabel msdos mkpart primary fat32 2048s 100% set 1 boot on
    mformat -i {{ build_dir }}/{{ img_name }}@@{{ fat_offset }} -F -v "BOOT" ::
    mcopy -i {{ build_dir }}/{{ img_name }}@@{{ fat_offset }} {{ build_dir }}/boot.scr ::/boot.scr

    # mmd -i {{ build_dir }}/{{ img_name }}@@{{ fat_offset }} ::/boot
    # mmd -i {{ build_dir }}/{{ img_name }}@@{{ fat_offset }} ::/boot/extlinux
    # mcopy -i {{ build_dir }}/{{ img_name }}@@{{ fat_offset }} ./extlinux.conf ::/boot/extlinux/extlinux.conf
    # mcopy -i {{ build_dir }}/{{ img_name }}@@{{ fat_offset }} {{ build_dir }}/kernel7.img ::/boot/kernel.img

run_uboot_arm: build_qemu_uboot_script build_7
    qemu-system-arm --machine virt --nographic --serial mon:stdio --no-reboot --bios $UBOOT_ARM --semihosting -drive file={{ build_dir }}/{{ img_name }},format=raw,if=virtio,readonly=on -s

run_uboot_aarch64: build_qemu_uboot_script build_8
    qemu-system-aarch64 --machine virt --cpu cortex-a57 --bios $UBOOT_AARCH64 --no-reboot --nographic --serial mon:stdio --semihosting --drive file={{ build_dir }}/{{ img_name }},format=raw,if=virtio,readonly=on -s

run_uboot_riscv32: build_qemu_uboot_script build_riscv32
    # U-Boot env vars expect at least 256M RAM
    qemu-system-riscv32 --machine virt -m 256M --bios $UBOOT_RISCV32_BIOS -device loader,file=$UBOOT_RISCV32,addr=0x80200000 --no-reboot --nographic --serial mon:stdio --drive file={{ build_dir }}/{{ img_name }},format=raw,if=virtio,readonly=on -s -netdev user,id=net0 -device virtio-net-device,netdev=net0

run_uboot_riscv64: build_qemu_uboot_script build_riscv64
    # U-Boot env vars expect at least 256M RAM
    qemu-system-riscv64 --machine virt -m 256M --bios $UBOOT_RISCV64_BIOS -device loader,file=$UBOOT_RISCV64,addr=0x80200000 --no-reboot --nographic --serial mon:stdio --drive file={{ build_dir }}/{{ img_name }},format=raw,if=virtio,readonly=on -s -netdev user,id=net0 -device virtio-net-device,netdev=net0

serve:
    http-server {{ build_dir }} -p {{ port }}

[working-directory('arm')]
clippy_arm:
    cargo clippy --target armv6-none-eabihf
    cargo clippy --target armv6-none-eabihf --features semihosting
    cargo clippy --target armv7a-none-eabihf
    cargo clippy --target armv7a-none-eabihf --features semihosting

[working-directory('aarch64')]
clippy_aarch64:
    cargo clippy --target aarch64-unknown-none-softfloat
    cargo clippy --target aarch64-unknown-none-softfloat --features semihosting

[working-directory('riscv')]
clippy_riscv:
    cargo clippy --target riscv32imac-unknown-none-elf
    cargo clippy --target riscv64gc-unknown-none-elf

clippy: clippy_arm clippy_aarch64 clippy_riscv
