[package]
name = "user_mode_program"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "user_mode_program"
test = false
bench = false

[dependencies]
common = { version = "0.1.0", path = "../common", default-features = false, features = [
    "user_mode",
] }
x86_64 = "0.15.2"
