[package]
name = "riscv_loader"
version = "0.1.0"
edition = "2024"

[[bin]]
path = "./src/main.rs"
name = "kernel"
test = false
bench = false

[dependencies]
arbitrary-int = "2.1.1"
bitbybit = "2.0.0"
loader = { version = "0.1.0", path = "../loader" }
riscv = { version = "0.16.0", features = ["s-mode"] }
sbi = "0.3.0"
