[package]
name = "kernel"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
embedded-graphics = "0.8.1"
limine = "0.4"
log = "0.4.27"
owo-colors = "4.2.1"
spinning_top = "0.3.0"
uart_16550 = "0.3.2"
unicode-segmentation = "1.12.0"
x86_64 = "0.15.2"

[[bin]]
name = "kernel"
test = false
bench = false
