[package]
name = "common"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
bincode = { version = "2.0.1", default-features = false, features = ["derive"] }
zerocopy = "0.8.25"

[features]
user_mode = []
kernel = []
default = ["user_mode", "kernel"]
