[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[[bin]]
path = "./src/main.rs"
name = "kernel"
test = false
bench = false

[dependencies]
fdt-raw = "0.2.0"
kernel_lib = { version = "0.1.0", path = "../kernel" }
log = "0.4.29"
riscv = { version = "0.16.0", features = ["s-mode"] }
sbi = "0.3.0"
