#![no_std]
#![feature(maybe_uninit_slice, sync_unsafe_cell)]
extern crate alloc;

mod elf_segment_flags;
mod env;
mod frame_buffer_embedded_graphics;
mod frame_buffer_info;
mod rgb_pixel_info;
mod slice_data;
mod syscall;
mod syscall_alloc;
mod syscall_alloc_stack;
mod syscall_channel;
mod syscall_exists;
mod syscall_exit_process;
mod syscall_exit_thread;
mod syscall_frame_buffer;
mod syscall_futex;
mod syscall_get_thread_id;
mod syscall_keyboard;
mod syscall_log;
mod syscall_map_module;
mod syscall_mouse;
mod syscall_read_event_stream;
mod syscall_spawn_process;
mod syscall_spawn_thread;
mod syscall_terminate_process;
mod syscall_wait_until_event;

pub use elf_segment_flags::*;
pub use env::*;
pub use frame_buffer_embedded_graphics::*;
pub use frame_buffer_info::*;
pub use rgb_pixel_info::*;
pub use slice_data::SliceData;
pub use syscall::*;
pub use syscall_alloc::*;
pub use syscall_alloc_stack::*;
pub use syscall_channel::*;
pub use syscall_exists::*;
pub use syscall_exit_process::*;
pub use syscall_exit_thread::*;
pub use syscall_frame_buffer::*;
pub use syscall_futex::*;
pub use syscall_get_thread_id::*;
pub use syscall_keyboard::*;
pub use syscall_log::*;
pub use syscall_map_module::*;
pub use syscall_mouse::*;
pub use syscall_read_event_stream::*;
pub use syscall_spawn_process::*;
pub use syscall_spawn_thread::*;
pub use syscall_terminate_process::*;
pub use syscall_wait_until_event::*;
