build_dir:
    mkdir -p build

build: build_dir
    cargo objcopy --target armv6-none-eabihf --features qemu,semihosting -- -O binary build/kernel.img

build_7: build_dir
    cargo objcopy --target armv7a-none-eabihf --features qemu,semihosting -- -O binary build/kernel7.img

build_8: build_dir
    cargo objcopy --target aarch64-unknown-none-softfloat --features qemu,semihosting -- -O binary build/kernel8.img

run_0: build
    qemu-system-arm --machine raspi0 --nographic --serial mon:stdio --no-reboot --kernel build/kernel.img --semihosting

run_1: build
    qemu-system-arm --machine raspi1ap --nographic --serial mon:stdio --no-reboot --kernel build/kernel.img --semihosting

run_2: build_7
    qemu-system-arm --machine raspi2b --nographic --serial mon:stdio --no-reboot --kernel build/kernel7.img --semihosting

run_3: build_8
    qemu-system-aarch64 --machine raspi3b --nographic --serial mon:stdio --no-reboot --kernel build/kernel8.img --semihosting -d int --trace "bcm2835_systmr_*"

run_4: build_8
    qemu-system-aarch64 --machine raspi4b --nographic --serial mon:stdio --no-reboot --kernel build/kernel8.img --semihosting -d int --trace "bcm2835_systmr_*"

clippy:
    cargo clippy --target armv6-none-eabihf --features qemu,semihosting
    cargo clippy --target armv7a-none-eabihf --features qemu,semihosting
    cargo clippy --target aarch64-unknown-none-softfloat --features qemu,semihosting
